import { StyleSheet } from 'react-native';
import { RFValue } from 'react-native-responsive-fontsize';

const createStyles = (theme) => StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  blurView: {
    ...StyleSheet.absoluteFillObject,
  },
  backdrop: {
    flex: 1,
    backgroundColor: theme.dark ? 'rgba(0, 0, 0, 0.8)' : 'rgba(0, 0, 0, 0.55)',
  },
  modalContainer: {
    backgroundColor: theme.colors.background,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    width: '100%',
    maxHeight: '90%',
    minHeight: '65%',
    paddingBottom: 16,
    paddingHorizontal: 18,
    alignSelf: 'center',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 24,
  },
  dragHandle: {
    width: 60,
    height: 5,
    borderRadius: 3,
    backgroundColor: theme.colors.border,
    alignSelf: 'center',
    marginTop: 12,
    marginBottom: 16,
    opacity: 0.7,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginBottom: 8,
  },
  headerAvatarWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 12,
  },
  headerAvatar: {
    width: 56,
    height: 56,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerAvatarText: {
    fontSize: RFValue(20),
    fontWeight: '800',
    letterSpacing: -0.5,
  },
  headerTitles: {
    flex: 1,
    gap: 6,
  },
  headerName: {
    fontSize: RFValue(16.5),
    fontWeight: '700',
    color: theme.colors.text,
    letterSpacing: -0.3,
  },
  headerBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 10,
  },
  headerBadgeText: {
    fontSize: RFValue(11),
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  closeButton: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: theme.colors.card,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 0,
    paddingBottom: 24,
    gap: 12,
  },
  sectionCard: {
    backgroundColor: theme.colors.card,
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: theme.colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: theme.dark ? 0.35 : 0.08,
    shadowRadius: 12,
    elevation: 6,
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: RFValue(12.5),
    fontWeight: '700',
    color: theme.colors.text,
    marginBottom: 12,
    letterSpacing: -0.2,
  },
  sectionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 6,
  },
  sectionIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionTexts: {
    flex: 1,
    gap: 4,
  },
  sectionLabel: {
    fontSize: RFValue(11),
    fontWeight: '700',
    color: theme.colors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  sectionValue: {
    fontSize: RFValue(14),
    fontWeight: '700',
    color: theme.colors.text,
    letterSpacing: -0.2,
  },
  copyButton: {
    padding: 8,
  },
  qrRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  qrText: {
    flex: 1,
    fontSize: RFValue(13),
    fontWeight: '700',
    color: theme.colors.primary,
    letterSpacing: -0.2,
  },
  qrActionsRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 12,
  },
  qrActionButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  qrActionText: {
    fontSize: RFValue(12),
    fontWeight: '700',
  },
  qrDisplay: {
    marginTop: 12,
    alignItems: 'center',
  },
  resendButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.primary,
    paddingVertical: 14,
    borderRadius: 12,
    marginTop: 16,
    gap: 8,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 4,
  },
  resendButtonText: {
    color: '#FFFFFF',
    fontSize: RFValue(13),
    fontWeight: '700',
    letterSpacing: -0.2,
  },
});

export default createStyles;
