import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  // --- Containers ---
  container: {
    flex: 1,
    backgroundColor: '#f8fafc',
  },
  content: {
    padding: 16,
  },
  header: {
    alignItems: 'center',
    paddingVertical: 16,
    marginBottom: 16,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1e293b',
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerTitleText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1e293b',
    marginLeft: 8,
  },

  // --- Tabs ---
  tabsContainer: {
    flexDirection: 'row',
    borderRadius: 12,
    padding: 4,
    gap: 6,
    marginBottom: 16,
    marginHorizontal: 16,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.3s ease',
  },
  tabButtonActive: {
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  tabText: {
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 0.3,
  },
  tabTextActive: {
    fontWeight: '700',
  },
  tabBadge: {
    backgroundColor: '#3b82f6',
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 2,
    marginLeft: 6,
    minWidth: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabBadgeText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '700',
  },
  tabContent: {
    marginTop: 8,
  },

  // --- Status Filter Tabs ---
  statusFilterContainer: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 16,
    paddingHorizontal: 16,
  },
  statusFilterTab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 4,
    borderRadius: 10,
    borderWidth: 1,
    gap: 4,
  },
  statusFilterText: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.2,
    textAlign: 'center',
    flexShrink: 1,
    flexWrap: 'wrap',
  },
  statusFilterBadge: {
    minWidth: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  statusFilterBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#ffffff',
  },

  // --- Categories grid ---
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 8,
  },
  categoryCard: {
    width: '48%',
    backgroundColor: 'white',
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 130,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
    overflow: 'hidden',
  },
  categoryCardPressed: {
    transform: [{ scale: 0.96 }],
    shadowOpacity: 0.12,
    elevation: 6,
  },
  categoryIconContainer: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  categoryTitle: {
    fontWeight: '700',
    color: '#1e293b',
    fontSize: 14,
    textAlign: 'center',
    marginTop: 4,
    letterSpacing: 0.2,
  },
  categoryCount: {
    fontSize: 11,
    color: '#64748b',
    marginTop: 4,
    fontWeight: '600',
  },

  // --- Form ---
  formHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  formTitle: { fontSize: 20, fontWeight: 'bold', color: '#1e293b', marginBottom: 4 },
  formSubtitle: { fontSize: 14, color: '#64748b', marginBottom: 16, fontWeight: '600' },
  inputGroup: { marginBottom: 16 },
  label: { fontSize: 14, fontWeight: '600', color: '#475569', marginBottom: 8 },
  labelRow: { 
    flexDirection: 'row', 
    justifyContent: 'space-between', 
    alignItems: 'center', 
    marginBottom: 8 
  },
  charCounter: { 
    fontSize: 12, 
    fontWeight: '600', 
    color: '#64748b' 
  },
  validationText: {
    fontSize: 12,
    marginTop: 4,
    fontWeight: '500',
  },
  input: {
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 16,
  },
  textarea: { minHeight: 100, textAlignVertical: 'top' },
  attachmentButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: 'dashed',
  },
  attachmentButtonText: { marginLeft: 8, fontSize: 16, fontWeight: '600' },

  // attachment preview & thumbnails
  attachmentPreviewContainer: { position: 'relative', marginTop: 8 },
  attachmentImage: { width: '100%', height: 200, borderRadius: 8 },
  removeAttachmentButton: { position: 'absolute', top: 8, right: 8, backgroundColor: 'rgba(255,255,255,0.8)', borderRadius: 16, padding: 4 },
  attachmentsRow: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 8 },
  thumbnailWrapper: { width: 100, height: 100, marginRight: 8, marginBottom: 8, position: 'relative' },
  thumbnail: { width: '100%', height: '100%', borderRadius: 8, backgroundColor: '#e5e7eb' },
  progressBarContainer: { position: 'absolute', left: 0, right: 0, bottom: 0, height: 6, backgroundColor: '#f1f5f9', borderBottomLeftRadius: 8, borderBottomRightRadius: 8, overflow: 'hidden' },
  progressBar: { height: '100%', width: '0%', backgroundColor: '#2563eb' },

  radioGroup: { flexDirection: 'row', justifyContent: 'space-around', marginTop: 8 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)' },
  modalOption: { paddingVertical: 14, paddingHorizontal: 16, borderBottomWidth: 1, borderBottomColor: '#e6eef8' },
  modalOptionText: { fontSize: 16, fontWeight: '600' },
  modalCancel: { borderBottomWidth: 0, marginTop: 8 },
  radioButton: { flexDirection: 'row', alignItems: 'center' },
  radioCircle: { height: 20, width: 20, borderRadius: 10, borderWidth: 2, borderColor: '#2563eb', alignItems: 'center', justifyContent: 'center', marginRight: 8 },
  radioDot: { height: 10, width: 10, borderRadius: 5, backgroundColor: '#2563eb' },

  submitButton: { 
    backgroundColor: '#2563eb', 
    padding: 16, 
    borderRadius: 8, 
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    shadowColor: '#2563eb',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  submitButtonText: { color: 'white', fontSize: 16, fontWeight: 'bold' },

  // --- Confirmation Screen ---
  confirmationContainer: { 
    flex: 1, 
    alignItems: 'center', 
    justifyContent: 'center', 
    padding: 16,
    paddingTop: 12,
    paddingBottom: 12,
  },
  successIconContainer: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    shadowColor: '#10b981',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  confirmationTitle: { 
    fontSize: 20, 
    fontWeight: '800', 
    marginBottom: 4,
    textAlign: 'center',
    letterSpacing: 0.3,
  },
  confirmationText: { 
    fontSize: 13, 
    color: '#64748b', 
    textAlign: 'center', 
    marginBottom: 12,
    lineHeight: 18,
  },
  protocolContainer: { 
    backgroundColor: '#f8fafc', 
    borderWidth: 2, 
    borderRadius: 12, 
    padding: 12, 
    marginVertical: 10, 
    alignItems: 'center',
    borderStyle: 'dashed',
    width: '100%',
    maxWidth: 260,
  },
  protocolLabel: { 
    fontSize: 9, 
    fontWeight: '600', 
    textTransform: 'uppercase', 
    letterSpacing: 0.8, 
    marginBottom: 4,
    opacity: 0.7,
  },
  protocolRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 3,
  },
  protocolNumber: { 
    fontSize: 16, 
    fontWeight: '800', 
    letterSpacing: 0.6,
  },
  protocolHint: {
    fontSize: 9,
    fontWeight: '500',
    opacity: 0.6,
    marginTop: 1,
  },
  summaryCard: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    padding: 12,
    width: '100%',
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 1,
  },
  summaryTitle: {
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 8,
    color: '#1e293b',
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 5,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  summaryLabel: {
    fontSize: 12,
    fontWeight: '500',
    color: '#64748b',
  },
  summaryValue: {
    fontSize: 12,
    fontWeight: '600',
    color: '#1e293b',
    flex: 1,
    textAlign: 'right',
  },
  timelineCard: {
    backgroundColor: '#eff6ff',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#3b82f6',
    padding: 12,
    width: '100%',
    marginBottom: 10,
  },
  timelineTitle: {
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 8,
    color: '#1e40af',
  },
  timelineStep: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
    gap: 8,
  },
  timelineDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#3b82f6',
  },
  timelineText: {
    fontSize: 11,
    fontWeight: '500',
    color: '#334155',
    flex: 1,
  },
  confirmationActions: {
    width: '100%',
    gap: 8,
  },
  actionButtonOutline: {
    borderWidth: 2,
    borderRadius: 10,
    paddingVertical: 9,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  actionButtonOutlineText: {
    fontSize: 13,
    fontWeight: '700',
  },
  actionButtonPrimary: {
    backgroundColor: '#3b82f6',
    borderRadius: 10,
    paddingVertical: 11,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#3b82f6',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  actionButtonPrimaryText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },
  actionButtonGhost: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionButtonGhostText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#64748b',
  },

  // --- Other Confirmation Styles ---
  confirmationTitle: { 
    fontSize: 24, 
    fontWeight: 'bold', 
    marginTop: 16 
  },
  confirmationText: { 
    fontSize: 16, 
    color: '#64748b', 
    textAlign: 'center', 
    marginVertical: 8 
  },

  // issues list
  accordionItem: { backgroundColor: 'white', borderRadius: 12, borderWidth: 1, borderColor: '#e2e8f0', marginBottom: 12, overflow: 'hidden' },
  accordionTrigger: { padding: 16, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  triggerLeft: { flex: 1 },
  accordionTitle: { fontSize: 16, fontWeight: 'bold', color: '#1e293b' },
  accordionSubtitle: { fontSize: 12, color: '#64748b', marginTop: 4 },
  statusBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
  statusBadgeText: { fontSize: 12, fontWeight: '600' },
  accordionContent: { paddingHorizontal: 16, paddingBottom: 16, borderTopWidth: 1, borderTopColor: '#f1f5f9' },

  // comments
  commentBubble: { maxWidth: '85%', padding: 12, borderRadius: 12, marginBottom: 12 },
  commentText: { fontSize: 14 },
  commentDate: { fontSize: 10, marginTop: 4, textAlign: 'right' },
  moradorBubble: { backgroundColor: '#2563eb', alignSelf: 'flex-end' },
  sindicoBubble: { backgroundColor: '#f1f5f9', alignSelf: 'flex-start' },
  moradorText: { color: 'white' },
  sindicoText: { color: '#1e293b' },

  // Message composer
  messageContainer: { flexDirection: 'row', alignItems: 'flex-end', marginTop: 12, padding: 8, borderRadius: 10, borderWidth: 1, borderColor: '#e6eef8' },
  messageInput: { flex: 1, minHeight: 40, maxHeight: 120, paddingHorizontal: 10, paddingVertical: 8, borderRadius: 8, backgroundColor: 'transparent' },
  sendButton: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8, marginLeft: 8, justifyContent: 'center', alignItems: 'center' },
  sendButtonText: { fontWeight: '700', fontSize: 14, color: '#fff' },

  // Protocol display
  protocolContainer: { 
    backgroundColor: '#f8fafc', 
    borderWidth: 2, 
    borderRadius: 12, 
    padding: 16, 
    marginVertical: 16, 
    alignItems: 'center',
    borderStyle: 'dashed'
  },
  protocolLabel: { 
    fontSize: 12, 
    fontWeight: '500', 
    textTransform: 'uppercase', 
    letterSpacing: 1, 
    marginBottom: 4 
  },
  protocolNumber: { 
    fontSize: 18, 
    fontWeight: 'bold', 
    letterSpacing: 1 
  },

  // --- ScrollView & Content ---
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 100,
  },
  formScrollContent: {
    paddingBottom: 120,
  },
  formContainer: {
    paddingHorizontal: 16,
    paddingTop: 8,
  },
});
