import { StyleSheet } from 'react-native';
import { RFValue } from 'react-native-responsive-fontsize';

const createStyles = (theme) => StyleSheet.create({
  container: {
    marginBottom: 12,
    marginHorizontal: 20,
  },
  cardWrapper: {
    borderRadius: 18,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: theme.dark ? 0.25 : 0.1,
    shadowRadius: 12,
    elevation: 4,
  },
  cardWrapperHighlight: {
    shadowColor: '#F59E0B',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 8,
  },
  cardGradient: {
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.card,
    position: 'relative',
    overflow: 'hidden',
    flexDirection: 'row',
    alignItems: 'center',
  },
  cardGradientHighlight: {
    borderWidth: 2,
    borderColor: '#F59E0B',
  },
  highlightBorder: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: '#F59E0B',
    opacity: 0.4,
    zIndex: 0,
  },
  leftSection: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 12,
    zIndex: 2,
  },
  avatarGradient: {
    width: 48,
    height: 48,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 3,
  },
  avatarText: {
    color: '#FFFFFF',
    fontSize: RFValue(16),
    fontWeight: '800',
    letterSpacing: -0.3,
  },
  infoContainer: {
    flex: 1,
    gap: 3,
  },
  visitorName: {
    fontSize: RFValue(14),
    fontWeight: '700',
    color: theme.colors.text,
    letterSpacing: -0.3,
  },
  visitorPhone: {
    fontSize: RFValue(11),
    fontWeight: '500',
    color: theme.colors.textSecondary,
    letterSpacing: -0.1,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 2,
    gap: 6,
  },
  metaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  metaDivider: {
    width: 2.5,
    height: 2.5,
    borderRadius: 1.25,
    backgroundColor: theme.colors.textSecondary,
    opacity: 0.35,
  },
  metaText: {
    fontSize: RFValue(10),
    fontWeight: '500',
    color: theme.colors.textSecondary,
    letterSpacing: -0.1,
  },
  rightSection: {
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
    gap: 8,
    zIndex: 2,
  },
  quickActionsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  approveButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#10B981',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#10B981',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  rejectButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#EF4444',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#EF4444',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  statusBadge: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 2,
  },
  arrowContainer: {
    opacity: 0.4,
  },
  decorLine: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: 3,
    height: '100%',
    opacity: 0.7,
    zIndex: 1,
  },
});

export default createStyles;
